spring:
    application:
        name: bucketz-registry
    cloud:
        config:
            uri: http://127.0.0.1:9000/bucketz-registry
server:
    port: 9001
    context-path: /bucketz-registry
    address: 0.0.0.0
    
eureka:
    instance:
        protocol: http
        ip-address: 127.0.0.1
        port: 9001
        context-path: /bucketz-registry
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: ${eureka.instance.protocol}://${eureka.instance.ip-address}:${eureka.instance.port}${eureka.instance.context-path}/eureka/
        register-with-eureka: false
        fetch-registry: false

logging:
    level:
        com:
            netflix:
                eureka: OFF
                discovery: OFF
